spring:
  application:
    name: mms-discovery-eureka

server:
  # 指定该Eureka实例的端口
  port: 8761

eureka:
  client:
    # 是否将自己注册到Eureka Server，默认为true
    register-with-eureka: false
    # 是否从Eureka Server获取注册信息，默认为true
    fetch-registry: false
    serviceUrl:
      # 设置与Eureka Server交互的地址，多个地址间可使用,分隔
      defaultZone: http://localhost:8761/eureka/